services:
  mtr:
    build:
      context: .
      dockerfile: Dockerfile.mtr
    container_name: mtr
    volumes:
      - ./results:/app/results
      - ./input:/app/input
    cap_add:
      - NET_RAW

  nmap:
    build:
      context: .
      dockerfile: Dockerfile.nmap
    container_name: nmap
    volumes:
      - ./results:/app/results
      - ./input:/app/input
    cap_add:
      - NET_RAW
  
  zgrab:
    image: ghcr.io/zmap/zgrab2:latest
    container_name: zgrab
    volumes:
      - ./results:/app/results
      - ./input:/app/input
