services:
  mtr:
    build:
      context: .
      dockerfile: Dockerfile.mtr
    container_name: mtr
    network_mode: "host"
    volumes:
      - ./results:/app/results
      - ./input:/app/input
    cap_add:
      - NET_RAW

  nmap:
    build:
      context: .
      dockerfile: Dockerfile.nmap
    container_name: nmap
    network_mode: "host"
    volumes:
      - ./results:/app/results
      - ./input:/app/input
    cap_add:
      - NET_RAW
  
  zgrab:
    image: ghcr.io/zmap/zgrab2:latest
    container_name: zgrab
    network_mode: "host"
    volumes:
      - ./results:/usr/bin/results
      - ./input:/usr/bin/input
    cap_add:
      - NET_RAW
  
  lzr:
    image: lzr
    container_name: lzr
    network_mode: "host"
    volumes:
      - ./results:/go/src/github.com/stanford-esrg/lzr/results
      - ./input:/go/src/github.com/stanford-esrg/lzr/input
    cap_add:
      - NET_RAW
      - NET_ADMIN

  zmap:
    image: zmap
    container_name: zmap
    network_mode: "host"
    volumes:
      - ./results:/root/results
      - ./input:/root/input
    cap_add:
      - NET_RAW
      - NET_ADMIN
